### ISSUE TITLE
Unexpected token: name (Exception)

### ISSUE THREAD

**Issue by RockNHawk** [lord-saumagen/TypeScript-LINQ#1]
ERROR in vendor.dc8d23889124525f7506.bundle.js from UglifyJs
Unexpected token: name (Exception) [vendor.dc8d23889124525f7506.bundle.js:43715,10]

When I use LINQ in Angular 2/4 with angular-cli and run "ng build --prod" to build release js, LINQ lib cause this Error.
If I remove all the LINQ references, that's OK.

**Comment by RockNHawk** [comment]
When I use LINQ in Angular 2/4 with angular-cli and run "ng build --prod" to build release js, LINQ lib cause this Error.
If I remove all the LINQ references, that's OK.

**Comment by lord-saumagen** [comment]
Dear Mr. darklx <https://github.com/darklx>,

I'm sorry to hear that you have problems to use my library.
Unfortunately your error descriptions is pretty much useless in order to
pinpoint the cause of your problems.
Your descriptions lacks all relevant information which might have helped to
track that error down.
I'm also not an Angular developer and can't give you any advise regarding
the interoperability of my LINQ fraemwork
and the Angular framework you chose to use.
That said, I will give you at least some more general advise which may help
to solve your problem.

Since the error message tells that the 'Exception' is an unknown token,
make sure that you have the all required files
referenced as described in the 'Usage' section on the project homepage.

[image: Inline images 1]

You should also make sure that they are referenced in the correct order.
I hope that you are aware, that the GITHUB solution is my development
solution and can be used as a starting point
for your own development if you wan't to enhance the given framework.
Open the solution in Visual Studio and will see that all modules are
declared as internal modules to simplify the
development process. If your project isn't strictly build with internal
modules (and I doubt that) problems are
predetermined.

As you certainly know, there is a npm package available for those scenarios
where you intent to use the library in your
own project instead of further enhance the library. That is also described
in the project homepage. Perhaps your problem
may resolve if you simply add the "typescript-linq" npm package to your
project.

[image: Inline images 2]

I hope this hints may help you to eliminate the error.

Good luck with that and kind regards, Lord Saumagen.

**Comment by RockNHawk** [comment]
@lord-saumagen 

Very thanks for your help.

When I use TypeScript-LINQ in angular 2/4 development environment' that's OK, but when I run
"ng build --prod" command to build release version js, appear this error.

Maybe It's UglifyJs's bug ("ng build --prod" command will use UglifyJs's to minify the js), I found the ionic framework have the same issue at yet.

> https://github.com/driftyco/ionic-app-scripts/issues/634
> @danbucholtz
> Seems like an uglifyjs bug. We have added support for babili and closure compiler to master to > mitigate some of the issues with uglifyjs. Please open an issue on their repo, we can't fix it 🐱

> Thanks,
> Dan


I saw that both ionic framework and TypeScript-LINQ framework have a class named "Exception",
Maybe change this class name will fix this problem.

I will have a try and send feedback or a pull request to you.

Thanks.
