### ISSUE TITLE
It would be nice to have a UMD wrapping 

### ISSUE THREAD

**Issue by aschekatihin** [lord-saumagen/TypeScript-LINQ#2]
This is a very useful module that implements both collections and linq so I'd like to use it on both client and server, however lack of UMD wrapping causes all sort of "exports is not defined" problems. 
Basically requirejs and wrapper like following would solve the problem:

```
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports"], factory);
    }
})(function (require, exports) {

... current source .....

});
```

**Comment by lord-saumagen** [comment]
Dear aschekatihin,
please pardon my late response.    
Unfortunately I'm not sure that I fully understand the problem you are describing. I'm currently using the modules you mention on client- and serverside without any problems. There is an npm package of this modules for serverside use and you can simply link the "TS-Linq.js" JavaScript file for clientside use.   
[Link to npm](https://www.npmjs.com/package/typescript-linq)  

![image](https://user-images.githubusercontent.com/9468599/28752449-f4cabec2-751f-11e7-8686-da3e407f0ca6.png)

The JavaScript file for clientside use:   

![image](https://user-images.githubusercontent.com/9468599/28752435-7fa32418-751f-11e7-9202-86ad3ad25595.png)   

Since your descriptions doesn't give a hint about what your are trying to do I'm not able to offer more support. I hope that this response will help to solve your problem.

With kind regards, Lord Saumagen.

**Comment by aschekatihin** [comment]
I guess it depends whether it work or not on what bundler/dependency resolver is in use. 
I'm using requirejs and when script is required() there is "exports is not defined error".

Without requirejs error is the same:
```
<!DOCTYPE html>
<html>
<head>
  	<title>Test</title>
</head>
<body>
    <script src="node_modules/typescript-linq/TS.js"></script>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/1819406/28868414-1530dcb4-7782-11e7-9fe6-b114488818c3.png)

Running in up to date Chrome.
![image](https://user-images.githubusercontent.com/1819406/28868560-81dfaa16-7782-11e7-81a8-962c207d9f48.png)
