### ISSUE TITLE
Custom providers or only collections

### ISSUE THREAD

**Issue by jeusdi** [lord-saumagen/TypeScript-LINQ#3]
Does it support the possibility to work with providers? Or it only works on collections? For example, could it be possible to create an odata provider?

**Comment by lord-saumagen** [comment]
Dear Mr. / Mrs. jeusdi,

the goal of this project was to bring the LINQ operators to TypeScript. I have no intention to create a 
LINQ 2 SQL solution. I'm sorry that I can't help you with your problem. Since there is now a whole bunch
of LINQ implementations for TypeScript, you might find a solution for your problem in one of this projects. 

Kind regards, Lord Saumagen.
